Header header

uint8 NORMAL=0
uint8 ERROR=1
uint8 STATE  

uint8 Battery_power

float64 Battery_current
float64 Battery_voltage

uint8 CHARGING = 1
uint8 NOCHARGING = 0
uint8 Charge_flag  

uint8 DOCKING_SENSOR_OFF = 0
uint8 DOCKING_SENSOR_ON = 1
uint8 Docking_sensor_flag

uint8 CHARGER_RELAY_OFF = 0
uint8 CHARGER_RELAY_ON = 1
uint8 Charger_relay_status

uint8 POWER_SAVING_OFF = 0
uint8 POWER_SAVING_ON = 1
uint8 Power_saving_mode

uint8 WIRE_CHARGING_MODE_OFF = 0
uint8 WIRE_CHARGING_MODE_ON = 1
uint8 Wire_charging_mode

uint8 DOCKING_CHARGE_DISABLE = 0
uint8 DOCKING_CHARGE_ENABLE = 1
uint8 Docking_charge_enable

uint8 BATTERY_NONFULL = 0
uint8 BATTERY_FULL = 1
uint8 Battery_full_flag

uint8 BATTERY_NONZERO = 0
uint8 BATTERY_ZERO = 1
uint8 Battery_empty_flag