Header header
string type

int32 DOOR_LOCK_STATE_UNLOCKED=0
int32 DOOR_LOCK_STATE_LOCKED=1
int32 DOOR_LOCK_STATE_ERROR=-1

uint8[] cargobox_id                                

int32[] door_lock_state             

bool[] door_open_state              

bool[] door_sensor_state                             

bool[] lamp_state                   

string led_color
string led_state

float32[] weight    

int8[] x_coordinate                

int8[] y_coordinate                  