Header header 

string joy_driver_status         

float32[] axes                   

bool[] button    


bool joy_driver_enable_button    
bool reduce_velocity_button      
bool raise_velocity_button       
bool reset_velocity_button       

float32 vel_scale              

float32 linear_velocity          
float32 angular_velocity         


uint8 AXIS_LEFT_STICK_X = 0
uint8 AXIS_LEFT_STICK_Y = 1
uint8 AXIS_RIGHT_STICK_X = 2
uint8 AXIS_RIGHT_STICK_Y = 3
uint8 AXIS_DPAD_X = 4
uint8 AXIS_DPAD_Y = 5
uint8 AXIS_LEFT_TRIGGER = 6
uint8 AXIS_RIGHT_TRIGGER = 7


uint8 BUTTON_A = 0
uint8 BUTTON_B = 1
uint8 BUTTON_X = 2
uint8 BUTTON_Y = 3
uint8 BUTTON_LB = 4
uint8 BUTTON_RB = 5
uint8 BUTTON_BACK = 6
uint8 BUTTON_START = 7
uint8 BUTTON_GUIDE = 8
uint8 BUTTON_LEFT_STICK = 9
uint8 BUTTON_RIGHT_STICK = 10

