Header header
string type

uint8 STATE_OFF=0
uint8 STATE_ON=1
uint8 STATE_BLINK=2
uint8 STATE_ERROR=3

uint8 LED_0_state
uint8 LED_1_state
uint8 LED_2_state
uint8 LED_3_state
uint8 LED_4_state
uint8 LED_5_state

uint8 SUB_LED_0_state
uint8 SUB_LED_1_state
uint8 SUB_LED_2_state
uint8 SUB_LED_3_state
uint8 SUB_LED_4_state
uint8 SUB_LED_5_state

uint8 LED_bar_color
uint8 LED_bar_state

uint8 LED_bar2_color
uint8 LED_bar2_state

uint8 LED_BAR_OFF = 0
uint8 LED_BAR_RED = 1
uint8 LED_BAR_GREEN = 2
uint8 LED_BAR_YELLOW = 3
uint8 LED_BAR_BLUE = 4
uint8 LED_BAR_MAGENTA = 5
uint8 LED_BAR_CYAN = 6
uint8 LED_BAR_WHITE = 7
