Header header

uint8 NOT_COMPLETE = 0

uint8 FORWARD_COMPLETE = 1
uint8 BACKWARD_COMPLETE = 2

uint8 hand_grip_forward_backward_report
uint8 cylinder_forward_backward_report
uint8 battery_cylinder_forward_backward_report

uint8 LOCK_COMPLETE = 1
uint8 UNLOCK_COMPLETE = 2

uint8 magazine01_lock_unlock_report
uint8 magazine02_lock_unlock_report

uint8 UP_COMPLETE = 1
uint8 DOWN_COMPLETE = 2

uint8 cylinder_up_down_report