int32 START = 0
int32 STOP = 1
int32 command

int32 id

float64 localized_line_A_x
float64 localized_line_A_y
float64 localized_line_B_x
float64 localized_line_B_y

int32 HANA_MACHINE_LONG = 1
int32 HANA_MACHINE_SHORT_SINGLE_EDGE = 2
int32 HANA_STOCKER = 3
int32 HANA_MACHINE_SHORT_DOUBLE_EDGE = 4
int32 NEPESARK_SHELF = 5
int32 type

float64 equipment_desired_x
float64 equipment_desired_y
---
int32 SUCCESS = 1
int32 NOT_READY = -1
int32 WRONG_COMMAND = -99

int32 result
