string type

uint8 START = 0
uint8 STOP = 1
uint8 PAUSE = 2
uint8 RESUME = 3
uint8 RESET_KALMAN = 4
uint8 GET_STATION = 5
uint8 command

string frame_name
geometry_msgs/Pose2D current_robot_pose
geometry_msgs/Pose2D candidate_pose

float64 roi_length

string extra_field
---
int32 SUCCESS = 1
int32 FAIL = -1
int32 ERROR = -999

int32 INVALID_MODE = -10
int32 INVALID_STATE= -11
int32 INVALID_COMMAND = -12
int32 INVALID_TYPE = -13
int32 INVALID_FRAME = -14
int32 INVALID_CURRENT = -15

int32 NOT_WORKING_DUETO_TOO_CLOSED = -20
int32 FAIL_DUETO_BOUND_ERROR = -21
int32 FAIL_DUETO_SIZE_ERROR = -22
int32 FAIL_DUETO_LENGTH_ERROR = -23

int32 result

bool is_find

geometry_msgs/Pose2D estimated_station_pose
string extra_field
