// Generated by gencpp from file twinny_msgs/CargoBoxLEDCommand.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_CARGOBOXLEDCOMMAND_H
#define TWINNY_MSGS_MESSAGE_CARGOBOXLEDCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct CargoBoxLEDCommand_
{
  typedef CargoBoxLEDCommand_<ContainerAllocator> Type;

  CargoBoxLEDCommand_()
    : header()
    , cargobox_id(0)
    , cargobox_led_id(0)
    , cargobox_led_status(0)  {
    }
  CargoBoxLEDCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cargobox_id(0)
    , cargobox_led_id(0)
    , cargobox_led_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _cargobox_id_type;
  _cargobox_id_type cargobox_id;

   typedef uint8_t _cargobox_led_id_type;
  _cargobox_led_id_type cargobox_led_id;

   typedef uint8_t _cargobox_led_status_type;
  _cargobox_led_status_type cargobox_led_status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(LED_BAR_OFF)
  #undef LED_BAR_OFF
#endif
#if defined(_WIN32) && defined(LED_BAR_RED)
  #undef LED_BAR_RED
#endif
#if defined(_WIN32) && defined(LED_BAR_GREEN)
  #undef LED_BAR_GREEN
#endif
#if defined(_WIN32) && defined(LED_BAR_YELLOW)
  #undef LED_BAR_YELLOW
#endif
#if defined(_WIN32) && defined(LED_BAR_BLUE)
  #undef LED_BAR_BLUE
#endif
#if defined(_WIN32) && defined(LED_BAR_MAGENTA)
  #undef LED_BAR_MAGENTA
#endif
#if defined(_WIN32) && defined(LED_BAR_CYAN)
  #undef LED_BAR_CYAN
#endif
#if defined(_WIN32) && defined(LED_BAR_WHITE)
  #undef LED_BAR_WHITE
#endif
#if defined(_WIN32) && defined(STATE_OFF)
  #undef STATE_OFF
#endif
#if defined(_WIN32) && defined(STATE_ON)
  #undef STATE_ON
#endif
#if defined(_WIN32) && defined(STATE_BLINK)
  #undef STATE_BLINK
#endif

  enum {
    LED_BAR_OFF = 100u,
    LED_BAR_RED = 101u,
    LED_BAR_GREEN = 102u,
    LED_BAR_YELLOW = 103u,
    LED_BAR_BLUE = 104u,
    LED_BAR_MAGENTA = 105u,
    LED_BAR_CYAN = 106u,
    LED_BAR_WHITE = 107u,
    STATE_OFF = 0u,
    STATE_ON = 1u,
    STATE_BLINK = 2u,
  };


  typedef boost::shared_ptr< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> const> ConstPtr;

}; // struct CargoBoxLEDCommand_

typedef ::twinny_msgs::CargoBoxLEDCommand_<std::allocator<void> > CargoBoxLEDCommand;

typedef boost::shared_ptr< ::twinny_msgs::CargoBoxLEDCommand > CargoBoxLEDCommandPtr;
typedef boost::shared_ptr< ::twinny_msgs::CargoBoxLEDCommand const> CargoBoxLEDCommandConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cargobox_id == rhs.cargobox_id &&
    lhs.cargobox_led_id == rhs.cargobox_led_id &&
    lhs.cargobox_led_status == rhs.cargobox_led_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63d81b1bd2386d79a57290dc39a16fa5";
  }

  static const char* value(const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63d81b1bd2386d79ULL;
  static const uint64_t static_value2 = 0xa57290dc39a16fa5ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/CargoBoxLEDCommand";
  }

  static const char* value(const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"uint8 cargobox_id\n"
"uint8 cargobox_led_id\n"
"uint8 cargobox_led_status\n"
"\n"
"uint8 LED_BAR_OFF = 100\n"
"uint8 LED_BAR_RED = 101\n"
"uint8 LED_BAR_GREEN = 102\n"
"uint8 LED_BAR_YELLOW = 103\n"
"uint8 LED_BAR_BLUE = 104\n"
"uint8 LED_BAR_MAGENTA = 105\n"
"uint8 LED_BAR_CYAN = 106\n"
"uint8 LED_BAR_WHITE = 107\n"
"\n"
"uint8 STATE_OFF=0\n"
"uint8 STATE_ON=1\n"
"uint8 STATE_BLINK=2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cargobox_id);
      stream.next(m.cargobox_led_id);
      stream.next(m.cargobox_led_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CargoBoxLEDCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::CargoBoxLEDCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cargobox_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cargobox_id);
    s << indent << "cargobox_led_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cargobox_led_id);
    s << indent << "cargobox_led_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cargobox_led_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_CARGOBOXLEDCOMMAND_H
