// Generated by gencpp from file twinny_msgs/DesiredTrajectory.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_DESIREDTRAJECTORY_H
#define TWINNY_MSGS_MESSAGE_DESIREDTRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <twinny_msgs/RobotState.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct DesiredTrajectory_
{
  typedef DesiredTrajectory_<ContainerAllocator> Type;

  DesiredTrajectory_()
    : header()
    , command_mode(0)
    , state()  {
    }
  DesiredTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , command_mode(0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _command_mode_type;
  _command_mode_type command_mode;

   typedef std::vector< ::twinny_msgs::RobotState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::twinny_msgs::RobotState_<ContainerAllocator> >> _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NORMAL)
  #undef NORMAL
#endif
#if defined(_WIN32) && defined(E_STOP)
  #undef E_STOP
#endif

  enum {
    NORMAL = 0u,
    E_STOP = 2u,
  };


  typedef boost::shared_ptr< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct DesiredTrajectory_

typedef ::twinny_msgs::DesiredTrajectory_<std::allocator<void> > DesiredTrajectory;

typedef boost::shared_ptr< ::twinny_msgs::DesiredTrajectory > DesiredTrajectoryPtr;
typedef boost::shared_ptr< ::twinny_msgs::DesiredTrajectory const> DesiredTrajectoryConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator1> & lhs, const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.command_mode == rhs.command_mode &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator1> & lhs, const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b57abfbad7a15896be8327858d220b";
  }

  static const char* value(const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b57abfbad7a158ULL;
  static const uint64_t static_value2 = 0x96be8327858d220bULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/DesiredTrajectory";
  }

  static const char* value(const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint32 NORMAL=0\n"
"uint32 E_STOP=2\n"
"\n"
"uint32 command_mode\n"
"twinny_msgs/RobotState[] state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: twinny_msgs/RobotState\n"
"twinny_msgs/Pose3D pose\n"
"twinny_msgs/Pose3D velocity\n"
"================================================================================\n"
"MSG: twinny_msgs/Pose3D\n"
"Header header\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.command_mode);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesiredTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::DesiredTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::DesiredTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "command_mode: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.command_mode);
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::twinny_msgs::RobotState_<ContainerAllocator> >::stream(s, indent + "    ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_DESIREDTRAJECTORY_H
