// Generated by gencpp from file twinny_msgs/getHardwareParam.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_GETHARDWAREPARAM_H
#define TWINNY_MSGS_MESSAGE_GETHARDWAREPARAM_H

#include <ros/service_traits.h>


#include <twinny_msgs/getHardwareParamRequest.h>
#include <twinny_msgs/getHardwareParamResponse.h>


namespace twinny_msgs
{

struct getHardwareParam
{

typedef getHardwareParamRequest Request;
typedef getHardwareParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getHardwareParam
} // namespace twinny_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twinny_msgs::getHardwareParam > {
  static const char* value()
  {
    return "2ba2e28439eb9799620f616f7cd32879";
  }

  static const char* value(const ::twinny_msgs::getHardwareParam&) { return value(); }
};

template<>
struct DataType< ::twinny_msgs::getHardwareParam > {
  static const char* value()
  {
    return "twinny_msgs/getHardwareParam";
  }

  static const char* value(const ::twinny_msgs::getHardwareParam&) { return value(); }
};


// service_traits::MD5Sum< ::twinny_msgs::getHardwareParamRequest> should match
// service_traits::MD5Sum< ::twinny_msgs::getHardwareParam >
template<>
struct MD5Sum< ::twinny_msgs::getHardwareParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::getHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::getHardwareParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::getHardwareParamRequest> should match
// service_traits::DataType< ::twinny_msgs::getHardwareParam >
template<>
struct DataType< ::twinny_msgs::getHardwareParamRequest>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::getHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::getHardwareParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twinny_msgs::getHardwareParamResponse> should match
// service_traits::MD5Sum< ::twinny_msgs::getHardwareParam >
template<>
struct MD5Sum< ::twinny_msgs::getHardwareParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::getHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::getHardwareParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::getHardwareParamResponse> should match
// service_traits::DataType< ::twinny_msgs::getHardwareParam >
template<>
struct DataType< ::twinny_msgs::getHardwareParamResponse>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::getHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::getHardwareParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_GETHARDWAREPARAM_H
