// Generated by gencpp from file twinny_msgs/Kinematics_Mode.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_KINEMATICS_MODE_H
#define TWINNY_MSGS_MESSAGE_KINEMATICS_MODE_H

#include <ros/service_traits.h>


#include <twinny_msgs/Kinematics_ModeRequest.h>
#include <twinny_msgs/Kinematics_ModeResponse.h>


namespace twinny_msgs
{

struct Kinematics_Mode
{

typedef Kinematics_ModeRequest Request;
typedef Kinematics_ModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kinematics_Mode
} // namespace twinny_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twinny_msgs::Kinematics_Mode > {
  static const char* value()
  {
    return "7998890966523349a389338408eec21f";
  }

  static const char* value(const ::twinny_msgs::Kinematics_Mode&) { return value(); }
};

template<>
struct DataType< ::twinny_msgs::Kinematics_Mode > {
  static const char* value()
  {
    return "twinny_msgs/Kinematics_Mode";
  }

  static const char* value(const ::twinny_msgs::Kinematics_Mode&) { return value(); }
};


// service_traits::MD5Sum< ::twinny_msgs::Kinematics_ModeRequest> should match
// service_traits::MD5Sum< ::twinny_msgs::Kinematics_Mode >
template<>
struct MD5Sum< ::twinny_msgs::Kinematics_ModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::Kinematics_Mode >::value();
  }
  static const char* value(const ::twinny_msgs::Kinematics_ModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::Kinematics_ModeRequest> should match
// service_traits::DataType< ::twinny_msgs::Kinematics_Mode >
template<>
struct DataType< ::twinny_msgs::Kinematics_ModeRequest>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::Kinematics_Mode >::value();
  }
  static const char* value(const ::twinny_msgs::Kinematics_ModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twinny_msgs::Kinematics_ModeResponse> should match
// service_traits::MD5Sum< ::twinny_msgs::Kinematics_Mode >
template<>
struct MD5Sum< ::twinny_msgs::Kinematics_ModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::Kinematics_Mode >::value();
  }
  static const char* value(const ::twinny_msgs::Kinematics_ModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::Kinematics_ModeResponse> should match
// service_traits::DataType< ::twinny_msgs::Kinematics_Mode >
template<>
struct DataType< ::twinny_msgs::Kinematics_ModeResponse>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::Kinematics_Mode >::value();
  }
  static const char* value(const ::twinny_msgs::Kinematics_ModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_KINEMATICS_MODE_H
