// Generated by gencpp from file twinny_msgs/MonitorHeartBeatHz.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_MONITORHEARTBEATHZ_H
#define TWINNY_MSGS_MESSAGE_MONITORHEARTBEATHZ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct MonitorHeartBeatHz_
{
  typedef MonitorHeartBeatHz_<ContainerAllocator> Type;

  MonitorHeartBeatHz_()
    : header()
    , Motor_DriverA_Hz(0)
    , Motor_DriverB_Hz(0)
    , Motor_DriverC_Hz(0)
    , Motor_DriverD_Hz(0)
    , Motor_DriverE_Hz(0)
    , Motor_DriverF_Hz(0)
    , Motor_DriverG_Hz(0)
    , Motor_DriverH_Hz(0)  {
    }
  MonitorHeartBeatHz_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Motor_DriverA_Hz(0)
    , Motor_DriverB_Hz(0)
    , Motor_DriverC_Hz(0)
    , Motor_DriverD_Hz(0)
    , Motor_DriverE_Hz(0)
    , Motor_DriverF_Hz(0)
    , Motor_DriverG_Hz(0)
    , Motor_DriverH_Hz(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Motor_DriverA_Hz_type;
  _Motor_DriverA_Hz_type Motor_DriverA_Hz;

   typedef uint8_t _Motor_DriverB_Hz_type;
  _Motor_DriverB_Hz_type Motor_DriverB_Hz;

   typedef uint8_t _Motor_DriverC_Hz_type;
  _Motor_DriverC_Hz_type Motor_DriverC_Hz;

   typedef uint8_t _Motor_DriverD_Hz_type;
  _Motor_DriverD_Hz_type Motor_DriverD_Hz;

   typedef uint8_t _Motor_DriverE_Hz_type;
  _Motor_DriverE_Hz_type Motor_DriverE_Hz;

   typedef uint8_t _Motor_DriverF_Hz_type;
  _Motor_DriverF_Hz_type Motor_DriverF_Hz;

   typedef uint8_t _Motor_DriverG_Hz_type;
  _Motor_DriverG_Hz_type Motor_DriverG_Hz;

   typedef uint8_t _Motor_DriverH_Hz_type;
  _Motor_DriverH_Hz_type Motor_DriverH_Hz;





  typedef boost::shared_ptr< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> const> ConstPtr;

}; // struct MonitorHeartBeatHz_

typedef ::twinny_msgs::MonitorHeartBeatHz_<std::allocator<void> > MonitorHeartBeatHz;

typedef boost::shared_ptr< ::twinny_msgs::MonitorHeartBeatHz > MonitorHeartBeatHzPtr;
typedef boost::shared_ptr< ::twinny_msgs::MonitorHeartBeatHz const> MonitorHeartBeatHzConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator1> & lhs, const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Motor_DriverA_Hz == rhs.Motor_DriverA_Hz &&
    lhs.Motor_DriverB_Hz == rhs.Motor_DriverB_Hz &&
    lhs.Motor_DriverC_Hz == rhs.Motor_DriverC_Hz &&
    lhs.Motor_DriverD_Hz == rhs.Motor_DriverD_Hz &&
    lhs.Motor_DriverE_Hz == rhs.Motor_DriverE_Hz &&
    lhs.Motor_DriverF_Hz == rhs.Motor_DriverF_Hz &&
    lhs.Motor_DriverG_Hz == rhs.Motor_DriverG_Hz &&
    lhs.Motor_DriverH_Hz == rhs.Motor_DriverH_Hz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator1> & lhs, const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e75bac3d8efef67e052259a96f13d33";
  }

  static const char* value(const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e75bac3d8efef67ULL;
  static const uint64_t static_value2 = 0xe052259a96f13d33ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/MonitorHeartBeatHz";
  }

  static const char* value(const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"uint8 Motor_DriverA_Hz\n"
"uint8 Motor_DriverB_Hz\n"
"uint8 Motor_DriverC_Hz\n"
"uint8 Motor_DriverD_Hz\n"
"uint8 Motor_DriverE_Hz\n"
"uint8 Motor_DriverF_Hz\n"
"uint8 Motor_DriverG_Hz\n"
"uint8 Motor_DriverH_Hz\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Motor_DriverA_Hz);
      stream.next(m.Motor_DriverB_Hz);
      stream.next(m.Motor_DriverC_Hz);
      stream.next(m.Motor_DriverD_Hz);
      stream.next(m.Motor_DriverE_Hz);
      stream.next(m.Motor_DriverF_Hz);
      stream.next(m.Motor_DriverG_Hz);
      stream.next(m.Motor_DriverH_Hz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MonitorHeartBeatHz_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::MonitorHeartBeatHz_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Motor_DriverA_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverA_Hz);
    s << indent << "Motor_DriverB_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverB_Hz);
    s << indent << "Motor_DriverC_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverC_Hz);
    s << indent << "Motor_DriverD_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverD_Hz);
    s << indent << "Motor_DriverE_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverE_Hz);
    s << indent << "Motor_DriverF_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverF_Hz);
    s << indent << "Motor_DriverG_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverG_Hz);
    s << indent << "Motor_DriverH_Hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Motor_DriverH_Hz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_MONITORHEARTBEATHZ_H
