// Generated by gencpp from file twinny_msgs/MonitorPacketStowage.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_MONITORPACKETSTOWAGE_H
#define TWINNY_MSGS_MESSAGE_MONITORPACKETSTOWAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct MonitorPacketStowage_
{
  typedef MonitorPacketStowage_<ContainerAllocator> Type;

  MonitorPacketStowage_()
    : header()
    , id()
    , can1_rx()
    , can1_tx()
    , mcu_rx_adc()
    , mcu_tx_adc()  {
    }
  MonitorPacketStowage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , can1_rx(_alloc)
    , can1_tx(_alloc)
    , mcu_rx_adc(_alloc)
    , mcu_tx_adc(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _id_type;
  _id_type id;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _can1_rx_type;
  _can1_rx_type can1_rx;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _can1_tx_type;
  _can1_tx_type can1_tx;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _mcu_rx_adc_type;
  _mcu_rx_adc_type mcu_rx_adc;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _mcu_tx_adc_type;
  _mcu_tx_adc_type mcu_tx_adc;





  typedef boost::shared_ptr< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> const> ConstPtr;

}; // struct MonitorPacketStowage_

typedef ::twinny_msgs::MonitorPacketStowage_<std::allocator<void> > MonitorPacketStowage;

typedef boost::shared_ptr< ::twinny_msgs::MonitorPacketStowage > MonitorPacketStowagePtr;
typedef boost::shared_ptr< ::twinny_msgs::MonitorPacketStowage const> MonitorPacketStowageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator1> & lhs, const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.can1_rx == rhs.can1_rx &&
    lhs.can1_tx == rhs.can1_tx &&
    lhs.mcu_rx_adc == rhs.mcu_rx_adc &&
    lhs.mcu_tx_adc == rhs.mcu_tx_adc;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator1> & lhs, const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a7045a31936c524fdd5bbd3fb3ce238";
  }

  static const char* value(const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a7045a31936c524ULL;
  static const uint64_t static_value2 = 0xfdd5bbd3fb3ce238ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/MonitorPacketStowage";
  }

  static const char* value(const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header  \n"
"\n"
"uint8[] id                            \n"
"\n"
"uint8[] can1_rx                       \n"
"uint8[] can1_tx                       \n"
"\n"
"uint8[] mcu_rx_adc                  \n"
"uint8[] mcu_tx_adc                  \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.can1_rx);
      stream.next(m.can1_tx);
      stream.next(m.mcu_rx_adc);
      stream.next(m.mcu_tx_adc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MonitorPacketStowage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::MonitorPacketStowage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id[]" << std::endl;
    for (size_t i = 0; i < v.id.size(); ++i)
    {
      s << indent << "  id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.id[i]);
    }
    s << indent << "can1_rx[]" << std::endl;
    for (size_t i = 0; i < v.can1_rx.size(); ++i)
    {
      s << indent << "  can1_rx[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.can1_rx[i]);
    }
    s << indent << "can1_tx[]" << std::endl;
    for (size_t i = 0; i < v.can1_tx.size(); ++i)
    {
      s << indent << "  can1_tx[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.can1_tx[i]);
    }
    s << indent << "mcu_rx_adc[]" << std::endl;
    for (size_t i = 0; i < v.mcu_rx_adc.size(); ++i)
    {
      s << indent << "  mcu_rx_adc[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mcu_rx_adc[i]);
    }
    s << indent << "mcu_tx_adc[]" << std::endl;
    for (size_t i = 0; i < v.mcu_tx_adc.size(); ++i)
    {
      s << indent << "  mcu_tx_adc[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.mcu_tx_adc[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_MONITORPACKETSTOWAGE_H
