// Generated by gencpp from file twinny_msgs/ObstacleReport.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_OBSTACLEREPORT_H
#define TWINNY_MSGS_MESSAGE_OBSTACLEREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct ObstacleReport_
{
  typedef ObstacleReport_<ContainerAllocator> Type;

  ObstacleReport_()
    : header()
    , Sensor_number(0)
    , Distance()  {
    }
  ObstacleReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Sensor_number(0)
    , Distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Sensor_number_type;
  _Sensor_number_type Sensor_number;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _Distance_type;
  _Distance_type Distance;





  typedef boost::shared_ptr< ::twinny_msgs::ObstacleReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::ObstacleReport_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleReport_

typedef ::twinny_msgs::ObstacleReport_<std::allocator<void> > ObstacleReport;

typedef boost::shared_ptr< ::twinny_msgs::ObstacleReport > ObstacleReportPtr;
typedef boost::shared_ptr< ::twinny_msgs::ObstacleReport const> ObstacleReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::ObstacleReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::ObstacleReport_<ContainerAllocator1> & lhs, const ::twinny_msgs::ObstacleReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Sensor_number == rhs.Sensor_number &&
    lhs.Distance == rhs.Distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::ObstacleReport_<ContainerAllocator1> & lhs, const ::twinny_msgs::ObstacleReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::ObstacleReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::ObstacleReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::ObstacleReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e97cdc4a6c06095094927910baeaaf10";
  }

  static const char* value(const ::twinny_msgs::ObstacleReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe97cdc4a6c060950ULL;
  static const uint64_t static_value2 = 0x94927910baeaaf10ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/ObstacleReport";
  }

  static const char* value(const ::twinny_msgs::ObstacleReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"\n"
"uint8 Sensor_number\n"
"uint8[] Distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::ObstacleReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Sensor_number);
      stream.next(m.Distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::ObstacleReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::ObstacleReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Sensor_number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Sensor_number);
    s << indent << "Distance[]" << std::endl;
    for (size_t i = 0; i < v.Distance.size(); ++i)
    {
      s << indent << "  Distance[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Distance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_OBSTACLEREPORT_H
