// Generated by gencpp from file twinny_msgs/PingStatusReport.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_PINGSTATUSREPORT_H
#define TWINNY_MSGS_MESSAGE_PINGSTATUSREPORT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct PingStatusReport_
{
  typedef PingStatusReport_<ContainerAllocator> Type;

  PingStatusReport_()
    : header()
    , device_name()
    , device_ip()
    , ping_status(false)  {
    }
  PingStatusReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , device_name(_alloc)
    , device_ip(_alloc)
    , ping_status(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _device_name_type;
  _device_name_type device_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _device_ip_type;
  _device_ip_type device_ip;

   typedef uint8_t _ping_status_type;
  _ping_status_type ping_status;





  typedef boost::shared_ptr< ::twinny_msgs::PingStatusReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::PingStatusReport_<ContainerAllocator> const> ConstPtr;

}; // struct PingStatusReport_

typedef ::twinny_msgs::PingStatusReport_<std::allocator<void> > PingStatusReport;

typedef boost::shared_ptr< ::twinny_msgs::PingStatusReport > PingStatusReportPtr;
typedef boost::shared_ptr< ::twinny_msgs::PingStatusReport const> PingStatusReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::PingStatusReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::PingStatusReport_<ContainerAllocator1> & lhs, const ::twinny_msgs::PingStatusReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.device_name == rhs.device_name &&
    lhs.device_ip == rhs.device_ip &&
    lhs.ping_status == rhs.ping_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::PingStatusReport_<ContainerAllocator1> & lhs, const ::twinny_msgs::PingStatusReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::PingStatusReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::PingStatusReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::PingStatusReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7dc823ed209aaeabcd0a55272cee0bf";
  }

  static const char* value(const ::twinny_msgs::PingStatusReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7dc823ed209aaeaULL;
  static const uint64_t static_value2 = 0xbcd0a55272cee0bfULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/PingStatusReport";
  }

  static const char* value(const ::twinny_msgs::PingStatusReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string device_name\n"
"string device_ip\n"
"bool ping_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::PingStatusReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.device_name);
      stream.next(m.device_ip);
      stream.next(m.ping_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PingStatusReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::PingStatusReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::PingStatusReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "device_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.device_name);
    s << indent << "device_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.device_ip);
    s << indent << "ping_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ping_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_PINGSTATUSREPORT_H
