// Generated by gencpp from file twinny_msgs/PositionCompensatorCommand.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_POSITIONCOMPENSATORCOMMAND_H
#define TWINNY_MSGS_MESSAGE_POSITIONCOMPENSATORCOMMAND_H

#include <ros/service_traits.h>


#include <twinny_msgs/PositionCompensatorCommandRequest.h>
#include <twinny_msgs/PositionCompensatorCommandResponse.h>


namespace twinny_msgs
{

struct PositionCompensatorCommand
{

typedef PositionCompensatorCommandRequest Request;
typedef PositionCompensatorCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PositionCompensatorCommand
} // namespace twinny_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twinny_msgs::PositionCompensatorCommand > {
  static const char* value()
  {
    return "64c066ac648eab7e36cd5c86a14aa3c6";
  }

  static const char* value(const ::twinny_msgs::PositionCompensatorCommand&) { return value(); }
};

template<>
struct DataType< ::twinny_msgs::PositionCompensatorCommand > {
  static const char* value()
  {
    return "twinny_msgs/PositionCompensatorCommand";
  }

  static const char* value(const ::twinny_msgs::PositionCompensatorCommand&) { return value(); }
};


// service_traits::MD5Sum< ::twinny_msgs::PositionCompensatorCommandRequest> should match
// service_traits::MD5Sum< ::twinny_msgs::PositionCompensatorCommand >
template<>
struct MD5Sum< ::twinny_msgs::PositionCompensatorCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::PositionCompensatorCommand >::value();
  }
  static const char* value(const ::twinny_msgs::PositionCompensatorCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::PositionCompensatorCommandRequest> should match
// service_traits::DataType< ::twinny_msgs::PositionCompensatorCommand >
template<>
struct DataType< ::twinny_msgs::PositionCompensatorCommandRequest>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::PositionCompensatorCommand >::value();
  }
  static const char* value(const ::twinny_msgs::PositionCompensatorCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twinny_msgs::PositionCompensatorCommandResponse> should match
// service_traits::MD5Sum< ::twinny_msgs::PositionCompensatorCommand >
template<>
struct MD5Sum< ::twinny_msgs::PositionCompensatorCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::PositionCompensatorCommand >::value();
  }
  static const char* value(const ::twinny_msgs::PositionCompensatorCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::PositionCompensatorCommandResponse> should match
// service_traits::DataType< ::twinny_msgs::PositionCompensatorCommand >
template<>
struct DataType< ::twinny_msgs::PositionCompensatorCommandResponse>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::PositionCompensatorCommand >::value();
  }
  static const char* value(const ::twinny_msgs::PositionCompensatorCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_POSITIONCOMPENSATORCOMMAND_H
