// Generated by gencpp from file twinny_msgs/PowerSavingMode.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_POWERSAVINGMODE_H
#define TWINNY_MSGS_MESSAGE_POWERSAVINGMODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct PowerSavingMode_
{
  typedef PowerSavingMode_<ContainerAllocator> Type;

  PowerSavingMode_()
    : header()
    , Power_saving_mode_command(0)  {
    }
  PowerSavingMode_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Power_saving_mode_command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Power_saving_mode_command_type;
  _Power_saving_mode_command_type Power_saving_mode_command;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(POWER_SAVING_OFF)
  #undef POWER_SAVING_OFF
#endif
#if defined(_WIN32) && defined(POWER_SAVING_ON)
  #undef POWER_SAVING_ON
#endif

  enum {
    POWER_SAVING_OFF = 0u,
    POWER_SAVING_ON = 1u,
  };


  typedef boost::shared_ptr< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> const> ConstPtr;

}; // struct PowerSavingMode_

typedef ::twinny_msgs::PowerSavingMode_<std::allocator<void> > PowerSavingMode;

typedef boost::shared_ptr< ::twinny_msgs::PowerSavingMode > PowerSavingModePtr;
typedef boost::shared_ptr< ::twinny_msgs::PowerSavingMode const> PowerSavingModeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::PowerSavingMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::PowerSavingMode_<ContainerAllocator1> & lhs, const ::twinny_msgs::PowerSavingMode_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Power_saving_mode_command == rhs.Power_saving_mode_command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::PowerSavingMode_<ContainerAllocator1> & lhs, const ::twinny_msgs::PowerSavingMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0af11356e58cb52bb82c9160d6eec4c";
  }

  static const char* value(const ::twinny_msgs::PowerSavingMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0af11356e58cb52ULL;
  static const uint64_t static_value2 = 0xbb82c9160d6eec4cULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/PowerSavingMode";
  }

  static const char* value(const ::twinny_msgs::PowerSavingMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 POWER_SAVING_OFF = 0\n"
"uint8 POWER_SAVING_ON = 1\n"
"uint8 Power_saving_mode_command\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::PowerSavingMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Power_saving_mode_command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PowerSavingMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::PowerSavingMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::PowerSavingMode_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Power_saving_mode_command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Power_saving_mode_command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_POWERSAVINGMODE_H
