// Generated by gencpp from file twinny_msgs/resetHardwareParamRequest.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_RESETHARDWAREPARAMREQUEST_H
#define TWINNY_MSGS_MESSAGE_RESETHARDWAREPARAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace twinny_msgs
{
template <class ContainerAllocator>
struct resetHardwareParamRequest_
{
  typedef resetHardwareParamRequest_<ContainerAllocator> Type;

  resetHardwareParamRequest_()
    {
    }
  resetHardwareParamRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct resetHardwareParamRequest_

typedef ::twinny_msgs::resetHardwareParamRequest_<std::allocator<void> > resetHardwareParamRequest;

typedef boost::shared_ptr< ::twinny_msgs::resetHardwareParamRequest > resetHardwareParamRequestPtr;
typedef boost::shared_ptr< ::twinny_msgs::resetHardwareParamRequest const> resetHardwareParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/resetHardwareParamRequest";
  }

  static const char* value(const ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resetHardwareParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::twinny_msgs::resetHardwareParamRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_RESETHARDWAREPARAMREQUEST_H
