// Generated by gencpp from file twinny_msgs/SellingStartCommand.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_SELLINGSTARTCOMMAND_H
#define TWINNY_MSGS_MESSAGE_SELLINGSTARTCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct SellingStartCommand_
{
  typedef SellingStartCommand_<ContainerAllocator> Type;

  SellingStartCommand_()
    : header()
    , selling_flag(false)  {
    }
  SellingStartCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , selling_flag(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _selling_flag_type;
  _selling_flag_type selling_flag;





  typedef boost::shared_ptr< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SellingStartCommand_

typedef ::twinny_msgs::SellingStartCommand_<std::allocator<void> > SellingStartCommand;

typedef boost::shared_ptr< ::twinny_msgs::SellingStartCommand > SellingStartCommandPtr;
typedef boost::shared_ptr< ::twinny_msgs::SellingStartCommand const> SellingStartCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::SellingStartCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::SellingStartCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::SellingStartCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.selling_flag == rhs.selling_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::SellingStartCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::SellingStartCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f032b0a824008a30ea74bfa6397be14";
  }

  static const char* value(const ::twinny_msgs::SellingStartCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f032b0a824008a3ULL;
  static const uint64_t static_value2 = 0x0ea74bfa6397be14ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/SellingStartCommand";
  }

  static const char* value(const ::twinny_msgs::SellingStartCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"bool selling_flag\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::SellingStartCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.selling_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SellingStartCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::SellingStartCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::SellingStartCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "selling_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.selling_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_SELLINGSTARTCOMMAND_H
