// Generated by gencpp from file twinny_msgs/setHardwareParam.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_SETHARDWAREPARAM_H
#define TWINNY_MSGS_MESSAGE_SETHARDWAREPARAM_H

#include <ros/service_traits.h>


#include <twinny_msgs/setHardwareParamRequest.h>
#include <twinny_msgs/setHardwareParamResponse.h>


namespace twinny_msgs
{

struct setHardwareParam
{

typedef setHardwareParamRequest Request;
typedef setHardwareParamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setHardwareParam
} // namespace twinny_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twinny_msgs::setHardwareParam > {
  static const char* value()
  {
    return "01cf8f3fd0d9c08e7ae80062dcbc18f2";
  }

  static const char* value(const ::twinny_msgs::setHardwareParam&) { return value(); }
};

template<>
struct DataType< ::twinny_msgs::setHardwareParam > {
  static const char* value()
  {
    return "twinny_msgs/setHardwareParam";
  }

  static const char* value(const ::twinny_msgs::setHardwareParam&) { return value(); }
};


// service_traits::MD5Sum< ::twinny_msgs::setHardwareParamRequest> should match
// service_traits::MD5Sum< ::twinny_msgs::setHardwareParam >
template<>
struct MD5Sum< ::twinny_msgs::setHardwareParamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::setHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::setHardwareParamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::setHardwareParamRequest> should match
// service_traits::DataType< ::twinny_msgs::setHardwareParam >
template<>
struct DataType< ::twinny_msgs::setHardwareParamRequest>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::setHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::setHardwareParamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twinny_msgs::setHardwareParamResponse> should match
// service_traits::MD5Sum< ::twinny_msgs::setHardwareParam >
template<>
struct MD5Sum< ::twinny_msgs::setHardwareParamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::setHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::setHardwareParamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::setHardwareParamResponse> should match
// service_traits::DataType< ::twinny_msgs::setHardwareParam >
template<>
struct DataType< ::twinny_msgs::setHardwareParamResponse>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::setHardwareParam >::value();
  }
  static const char* value(const ::twinny_msgs::setHardwareParamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_SETHARDWAREPARAM_H
