// Generated by gencpp from file twinny_msgs/StationRecognizerCommand.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_STATIONRECOGNIZERCOMMAND_H
#define TWINNY_MSGS_MESSAGE_STATIONRECOGNIZERCOMMAND_H

#include <ros/service_traits.h>


#include <twinny_msgs/StationRecognizerCommandRequest.h>
#include <twinny_msgs/StationRecognizerCommandResponse.h>


namespace twinny_msgs
{

struct StationRecognizerCommand
{

typedef StationRecognizerCommandRequest Request;
typedef StationRecognizerCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StationRecognizerCommand
} // namespace twinny_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::twinny_msgs::StationRecognizerCommand > {
  static const char* value()
  {
    return "fc40b6d334b5e6c2cc71670efc1b918a";
  }

  static const char* value(const ::twinny_msgs::StationRecognizerCommand&) { return value(); }
};

template<>
struct DataType< ::twinny_msgs::StationRecognizerCommand > {
  static const char* value()
  {
    return "twinny_msgs/StationRecognizerCommand";
  }

  static const char* value(const ::twinny_msgs::StationRecognizerCommand&) { return value(); }
};


// service_traits::MD5Sum< ::twinny_msgs::StationRecognizerCommandRequest> should match
// service_traits::MD5Sum< ::twinny_msgs::StationRecognizerCommand >
template<>
struct MD5Sum< ::twinny_msgs::StationRecognizerCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::StationRecognizerCommand >::value();
  }
  static const char* value(const ::twinny_msgs::StationRecognizerCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::StationRecognizerCommandRequest> should match
// service_traits::DataType< ::twinny_msgs::StationRecognizerCommand >
template<>
struct DataType< ::twinny_msgs::StationRecognizerCommandRequest>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::StationRecognizerCommand >::value();
  }
  static const char* value(const ::twinny_msgs::StationRecognizerCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::twinny_msgs::StationRecognizerCommandResponse> should match
// service_traits::MD5Sum< ::twinny_msgs::StationRecognizerCommand >
template<>
struct MD5Sum< ::twinny_msgs::StationRecognizerCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::twinny_msgs::StationRecognizerCommand >::value();
  }
  static const char* value(const ::twinny_msgs::StationRecognizerCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::twinny_msgs::StationRecognizerCommandResponse> should match
// service_traits::DataType< ::twinny_msgs::StationRecognizerCommand >
template<>
struct DataType< ::twinny_msgs::StationRecognizerCommandResponse>
{
  static const char* value()
  {
    return DataType< ::twinny_msgs::StationRecognizerCommand >::value();
  }
  static const char* value(const ::twinny_msgs::StationRecognizerCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_STATIONRECOGNIZERCOMMAND_H
