// Generated by gencpp from file twinny_msgs/TurnSignalCommand.msg
// DO NOT EDIT!


#ifndef TWINNY_MSGS_MESSAGE_TURNSIGNALCOMMAND_H
#define TWINNY_MSGS_MESSAGE_TURNSIGNALCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace twinny_msgs
{
template <class ContainerAllocator>
struct TurnSignalCommand_
{
  typedef TurnSignalCommand_<ContainerAllocator> Type;

  TurnSignalCommand_()
    : header()
    , Command(0)  {
    }
  TurnSignalCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Command(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _Command_type;
  _Command_type Command;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(TURN_LEFT)
  #undef TURN_LEFT
#endif
#if defined(_WIN32) && defined(TURN_RIGHT)
  #undef TURN_RIGHT
#endif
#if defined(_WIN32) && defined(ALL)
  #undef ALL
#endif

  enum {
    OFF = 0u,
    TURN_LEFT = 1u,
    TURN_RIGHT = 2u,
    ALL = 3u,
  };


  typedef boost::shared_ptr< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TurnSignalCommand_

typedef ::twinny_msgs::TurnSignalCommand_<std::allocator<void> > TurnSignalCommand;

typedef boost::shared_ptr< ::twinny_msgs::TurnSignalCommand > TurnSignalCommandPtr;
typedef boost::shared_ptr< ::twinny_msgs::TurnSignalCommand const> TurnSignalCommandConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Command == rhs.Command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator1> & lhs, const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace twinny_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a90b548f2d6c123772559249a5f53f5";
  }

  static const char* value(const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a90b548f2d6c123ULL;
  static const uint64_t static_value2 = 0x772559249a5f53f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "twinny_msgs/TurnSignalCommand";
  }

  static const char* value(const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header  \n"
"\n"
"uint8 Command\n"
"\n"
"uint8 OFF=0\n"
"uint8 TURN_LEFT=1\n"
"uint8 TURN_RIGHT=2\n"
"uint8 ALL=3\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnSignalCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::twinny_msgs::TurnSignalCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::twinny_msgs::TurnSignalCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TWINNY_MSGS_MESSAGE_TURNSIGNALCOMMAND_H
