(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TYPE-VAL
          TYPE
          CONVEYOR1_STATUS-VAL
          CONVEYOR1_STATUS
          CONVEYOR2_STATUS-VAL
          CONVEYOR2_STATUS
          IS_LOADED_CONVEYOR1_1-VAL
          IS_LOADED_CONVEYOR1_1
          IS_LOADED_CONVEYOR1_2-VAL
          IS_LOADED_CONVEYOR1_2
          IS_LOADED_CONVEYOR2_1-VAL
          IS_LOADED_CONVEYOR2_1
          IS_LOADED_CONVEYOR2_2-VAL
          IS_LOADED_CONVEYOR2_2
          IS_ALARM_CONVEYOR1-VAL
          IS_ALARM_CONVEYOR1
          IS_ALARM_CONVEYOR2-VAL
          IS_ALARM_CONVEYOR2
          DOOR_OPEN_STATUS-VAL
          DOOR_OPEN_STATUS
          FALL_PREVENTION_DEVICE_STATUS-VAL
          FALL_PREVENTION_DEVICE_STATUS
))