(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HAND_GRIP_FORWARD_BACKWARD-VAL
          HAND_GRIP_FORWARD_BACKWARD
          CYLINDER_FORWARD_BACKWARD-VAL
          CYLINDER_FORWARD_BACKWARD
          BATTERY_CYLINDER_FORWARD_BACKWARD-VAL
          BATTERY_CYLINDER_FORWARD_BACKWARD
          MAGAZINE01_LOCK-VAL
          MAGAZINE01_LOCK
          MAGAZINE02_LOCK-VAL
          MAGAZINE02_LOCK
          CYLINDER_UP_DOWN-VAL
          CYLINDER_UP_DOWN
))