(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POWER_ACTUAL_3_3V_MONITORING-VAL
          POWER_ACTUAL_3_3V_MONITORING
          POWER_ACTUAL_5V_MONITORING-VAL
          POWER_ACTUAL_5V_MONITORING
          POWER_ACTUAL_12V_MONITORING-VAL
          POWER_ACTUAL_12V_MONITORING
          POWER_ACTUAL_24V_MONITORING-VAL
          POWER_ACTUAL_24V_MONITORING
          ROBOT_ACTUAL_3_3V_MONITORING-VAL
          ROBOT_ACTUAL_3_3V_MONITORING
          ROBOT_ACTUAL_5V_MONITORING-VAL
          ROBOT_ACTUAL_5V_MONITORING
          ROBOT_ACTUAL_12V_MONITORING-VAL
          ROBOT_ACTUAL_12V_MONITORING
          ROBOT_ACTUAL_24V_MONITORING-VAL
          ROBOT_ACTUAL_24V_MONITORING
))