(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MOTOR_POWER_RELAY_CONTROL-VAL
          MOTOR_POWER_RELAY_CONTROL
          PC_MCU_POWER_RELAY_CONTROL-VAL
          PC_MCU_POWER_RELAY_CONTROL
          CHARGER_START_COMMAND-VAL
          CHARGER_START_COMMAND
))