(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          HAND_GRIP_FORWARD_BACKWARD_REPORT-VAL
          HAND_GRIP_FORWARD_BACKWARD_REPORT
          CYLINDER_FORWARD_BACKWARD_REPORT-VAL
          CYLINDER_FORWARD_BACKWARD_REPORT
          BATTERY_CYLINDER_FORWARD_BACKWARD_REPORT-VAL
          BATTERY_CYLINDER_FORWARD_BACKWARD_REPORT
          MAGAZINE01_LOCK_UNLOCK_REPORT-VAL
          MAGAZINE01_LOCK_UNLOCK_REPORT
          MAGAZINE02_LOCK_UNLOCK_REPORT-VAL
          MAGAZINE02_LOCK_UNLOCK_REPORT
          CYLINDER_UP_DOWN_REPORT-VAL
          CYLINDER_UP_DOWN_REPORT
))