(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATE-VAL
          STATE
          BATTERY_POWER-VAL
          BATTERY_POWER
          BATTERY_CURRENT-VAL
          BATTERY_CURRENT
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          CHARGE_FLAG-VAL
          CHARGE_FLAG
          DOCKING_SENSOR_FLAG-VAL
          DOCKING_SENSOR_FLAG
          CHARGER_RELAY_STATUS-VAL
          CHARGER_RELAY_STATUS
          POWER_SAVING_MODE-VAL
          POWER_SAVING_MODE
          WIRE_CHARGING_MODE-VAL
          WIRE_CHARGING_MODE
          DOCKING_CHARGE_ENABLE-VAL
          DOCKING_CHARGE_ENABLE
          BATTERY_FULL_FLAG-VAL
          BATTERY_FULL_FLAG
          BATTERY_EMPTY_FLAG-VAL
          BATTERY_EMPTY_FLAG
))