(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          JOY_DRIVER_STATUS-VAL
          JOY_DRIVER_STATUS
          AXES-VAL
          AXES
          BUTTON-VAL
          BUTTON
          JOY_DRIVER_ENABLE_BUTTON-VAL
          JOY_DRIVER_ENABLE_BUTTON
          REDUCE_VELOCITY_BUTTON-VAL
          REDUCE_VELOCITY_BUTTON
          RAISE_VELOCITY_BUTTON-VAL
          RAISE_VELOCITY_BUTTON
          RESET_VELOCITY_BUTTON-VAL
          RESET_VELOCITY_BUTTON
          VEL_SCALE-VAL
          VEL_SCALE
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
))