(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          E_STOP_BUTTON-VAL
          E_STOP_BUTTON
          SW_0_TOGGLE-VAL
          SW_0_TOGGLE
          SW_1_TOGGLE-VAL
          SW_1_TOGGLE
          SW_2_TOGGLE-VAL
          SW_2_TOGGLE
          SW_3_TOGGLE-VAL
          SW_3_TOGGLE
          SW_4_TOGGLE-VAL
          SW_4_TOGGLE
          SW_5_TOGGLE-VAL
          SW_5_TOGGLE
          SUB_SW_0_TOGGLE-VAL
          SUB_SW_0_TOGGLE
          SUB_SW_1_TOGGLE-VAL
          SUB_SW_1_TOGGLE
          SUB_SW_2_TOGGLE-VAL
          SUB_SW_2_TOGGLE
          SUB_SW_3_TOGGLE-VAL
          SUB_SW_3_TOGGLE
          SUB_SW_4_TOGGLE-VAL
          SUB_SW_4_TOGGLE
          SUB_SW_5_TOGGLE-VAL
          SUB_SW_5_TOGGLE
          DOCKING_HALL_SENSOR-VAL
          DOCKING_HALL_SENSOR
          MOTOR_BRAKE-VAL
          MOTOR_BRAKE
          MAIN_POWER_STATE-VAL
          MAIN_POWER_STATE
          DOCKINGIR_POWER_STATE-VAL
          DOCKINGIR_POWER_STATE
))