(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TYPE-VAL
          TYPE
          LED_0_STATE-VAL
          LED_0_STATE
          LED_1_STATE-VAL
          LED_1_STATE
          LED_2_STATE-VAL
          LED_2_STATE
          LED_3_STATE-VAL
          LED_3_STATE
          LED_4_STATE-VAL
          LED_4_STATE
          LED_5_STATE-VAL
          LED_5_STATE
          SUB_LED_0_STATE-VAL
          SUB_LED_0_STATE
          SUB_LED_1_STATE-VAL
          SUB_LED_1_STATE
          SUB_LED_2_STATE-VAL
          SUB_LED_2_STATE
          SUB_LED_3_STATE-VAL
          SUB_LED_3_STATE
          SUB_LED_4_STATE-VAL
          SUB_LED_4_STATE
          SUB_LED_5_STATE-VAL
          SUB_LED_5_STATE
          LED_BAR_COLOR-VAL
          LED_BAR_COLOR
          LED_BAR_STATE-VAL
          LED_BAR_STATE
          LED_BAR2_COLOR-VAL
          LED_BAR2_COLOR
          LED_BAR2_STATE-VAL
          LED_BAR2_STATE
))