(cl:in-package twinny_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MOTOR_NUMBER-VAL
          MOTOR_NUMBER
          MOTOR_DRIVE_BRIDGE_STATUS-VAL
          MOTOR_DRIVE_BRIDGE_STATUS
          MOTOR_DRIVE_PROTECTION_STATUS-VAL
          MOTOR_DRIVE_PROTECTION_STATUS
          MOTOR_SYSTEM_PROTECTION_STATUS-VAL
          MOTOR_SYSTEM_PROTECTION_STATUS
          MOTOR_DRIVE_SYSTEM_STATUS-VAL
          MOTOR_DRIVE_SYSTEM_STATUS
          MOTOR_ERROR_LEVEL-VAL
          MOTOR_ERROR_LEVEL
))