# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from twinny_msgs/ConveyorStatusReport.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ConveyorStatusReport(genpy.Message):
  _md5sum = "edac1cb1f807055427a86099e42b8c69"
  _type = "twinny_msgs/ConveyorStatusReport"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
string type

int8 CONVEYOR_STATUS_REVERSE = -1
int8 CONVEYOR_STATUS_STOP = 0
int8 CONVEYOR_STATUS_FORWARD = 1

int8 conveyor1_status
int8 conveyor2_status

bool is_loaded_conveyor1_1
bool is_loaded_conveyor1_2
bool is_loaded_conveyor2_1
bool is_loaded_conveyor2_2

bool is_alarm_conveyor1
bool is_alarm_conveyor2

bool door_open_status

bool fall_prevention_device_status


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  # Pseudo-constants
  CONVEYOR_STATUS_REVERSE = -1
  CONVEYOR_STATUS_STOP = 0
  CONVEYOR_STATUS_FORWARD = 1

  __slots__ = ['header','type','conveyor1_status','conveyor2_status','is_loaded_conveyor1_1','is_loaded_conveyor1_2','is_loaded_conveyor2_1','is_loaded_conveyor2_2','is_alarm_conveyor1','is_alarm_conveyor2','door_open_status','fall_prevention_device_status']
  _slot_types = ['std_msgs/Header','string','int8','int8','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,type,conveyor1_status,conveyor2_status,is_loaded_conveyor1_1,is_loaded_conveyor1_2,is_loaded_conveyor2_1,is_loaded_conveyor2_2,is_alarm_conveyor1,is_alarm_conveyor2,door_open_status,fall_prevention_device_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ConveyorStatusReport, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.type is None:
        self.type = ''
      if self.conveyor1_status is None:
        self.conveyor1_status = 0
      if self.conveyor2_status is None:
        self.conveyor2_status = 0
      if self.is_loaded_conveyor1_1 is None:
        self.is_loaded_conveyor1_1 = False
      if self.is_loaded_conveyor1_2 is None:
        self.is_loaded_conveyor1_2 = False
      if self.is_loaded_conveyor2_1 is None:
        self.is_loaded_conveyor2_1 = False
      if self.is_loaded_conveyor2_2 is None:
        self.is_loaded_conveyor2_2 = False
      if self.is_alarm_conveyor1 is None:
        self.is_alarm_conveyor1 = False
      if self.is_alarm_conveyor2 is None:
        self.is_alarm_conveyor2 = False
      if self.door_open_status is None:
        self.door_open_status = False
      if self.fall_prevention_device_status is None:
        self.fall_prevention_device_status = False
    else:
      self.header = std_msgs.msg.Header()
      self.type = ''
      self.conveyor1_status = 0
      self.conveyor2_status = 0
      self.is_loaded_conveyor1_1 = False
      self.is_loaded_conveyor1_2 = False
      self.is_loaded_conveyor2_1 = False
      self.is_loaded_conveyor2_2 = False
      self.is_alarm_conveyor1 = False
      self.is_alarm_conveyor2 = False
      self.door_open_status = False
      self.fall_prevention_device_status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b8B().pack(_x.conveyor1_status, _x.conveyor2_status, _x.is_loaded_conveyor1_1, _x.is_loaded_conveyor1_2, _x.is_loaded_conveyor2_1, _x.is_loaded_conveyor2_2, _x.is_alarm_conveyor1, _x.is_alarm_conveyor2, _x.door_open_status, _x.fall_prevention_device_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.conveyor1_status, _x.conveyor2_status, _x.is_loaded_conveyor1_1, _x.is_loaded_conveyor1_2, _x.is_loaded_conveyor2_1, _x.is_loaded_conveyor2_2, _x.is_alarm_conveyor1, _x.is_alarm_conveyor2, _x.door_open_status, _x.fall_prevention_device_status,) = _get_struct_2b8B().unpack(str[start:end])
      self.is_loaded_conveyor1_1 = bool(self.is_loaded_conveyor1_1)
      self.is_loaded_conveyor1_2 = bool(self.is_loaded_conveyor1_2)
      self.is_loaded_conveyor2_1 = bool(self.is_loaded_conveyor2_1)
      self.is_loaded_conveyor2_2 = bool(self.is_loaded_conveyor2_2)
      self.is_alarm_conveyor1 = bool(self.is_alarm_conveyor1)
      self.is_alarm_conveyor2 = bool(self.is_alarm_conveyor2)
      self.door_open_status = bool(self.door_open_status)
      self.fall_prevention_device_status = bool(self.fall_prevention_device_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2b8B().pack(_x.conveyor1_status, _x.conveyor2_status, _x.is_loaded_conveyor1_1, _x.is_loaded_conveyor1_2, _x.is_loaded_conveyor2_1, _x.is_loaded_conveyor2_2, _x.is_alarm_conveyor1, _x.is_alarm_conveyor2, _x.door_open_status, _x.fall_prevention_device_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 10
      (_x.conveyor1_status, _x.conveyor2_status, _x.is_loaded_conveyor1_1, _x.is_loaded_conveyor1_2, _x.is_loaded_conveyor2_1, _x.is_loaded_conveyor2_2, _x.is_alarm_conveyor1, _x.is_alarm_conveyor2, _x.door_open_status, _x.fall_prevention_device_status,) = _get_struct_2b8B().unpack(str[start:end])
      self.is_loaded_conveyor1_1 = bool(self.is_loaded_conveyor1_1)
      self.is_loaded_conveyor1_2 = bool(self.is_loaded_conveyor1_2)
      self.is_loaded_conveyor2_1 = bool(self.is_loaded_conveyor2_1)
      self.is_loaded_conveyor2_2 = bool(self.is_loaded_conveyor2_2)
      self.is_alarm_conveyor1 = bool(self.is_alarm_conveyor1)
      self.is_alarm_conveyor2 = bool(self.is_alarm_conveyor2)
      self.door_open_status = bool(self.door_open_status)
      self.fall_prevention_device_status = bool(self.fall_prevention_device_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b8B = None
def _get_struct_2b8B():
    global _struct_2b8B
    if _struct_2b8B is None:
        _struct_2b8B = struct.Struct("<2b8B")
    return _struct_2b8B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
