# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from twinny_msgs/MonitorRobotBoard.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MonitorRobotBoard(genpy.Message):
  _md5sum = "feeef21295281612a29bf518f366cb43"
  _type = "twinny_msgs/MonitorRobotBoard"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header 

string Mode 
uint8 motorErrorIndex
uint8 pc_to_mcu_heartbeat_hz
bool pc_to_mcu_heartbeat_error
bool motor_to_mcu_heartbeat_error
bool can_error
bool lin_error



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','Mode','motorErrorIndex','pc_to_mcu_heartbeat_hz','pc_to_mcu_heartbeat_error','motor_to_mcu_heartbeat_error','can_error','lin_error']
  _slot_types = ['std_msgs/Header','string','uint8','uint8','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Mode,motorErrorIndex,pc_to_mcu_heartbeat_hz,pc_to_mcu_heartbeat_error,motor_to_mcu_heartbeat_error,can_error,lin_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MonitorRobotBoard, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Mode is None:
        self.Mode = ''
      if self.motorErrorIndex is None:
        self.motorErrorIndex = 0
      if self.pc_to_mcu_heartbeat_hz is None:
        self.pc_to_mcu_heartbeat_hz = 0
      if self.pc_to_mcu_heartbeat_error is None:
        self.pc_to_mcu_heartbeat_error = False
      if self.motor_to_mcu_heartbeat_error is None:
        self.motor_to_mcu_heartbeat_error = False
      if self.can_error is None:
        self.can_error = False
      if self.lin_error is None:
        self.lin_error = False
    else:
      self.header = std_msgs.msg.Header()
      self.Mode = ''
      self.motorErrorIndex = 0
      self.pc_to_mcu_heartbeat_hz = 0
      self.pc_to_mcu_heartbeat_error = False
      self.motor_to_mcu_heartbeat_error = False
      self.can_error = False
      self.lin_error = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B().pack(_x.motorErrorIndex, _x.pc_to_mcu_heartbeat_hz, _x.pc_to_mcu_heartbeat_error, _x.motor_to_mcu_heartbeat_error, _x.can_error, _x.lin_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mode = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.motorErrorIndex, _x.pc_to_mcu_heartbeat_hz, _x.pc_to_mcu_heartbeat_error, _x.motor_to_mcu_heartbeat_error, _x.can_error, _x.lin_error,) = _get_struct_6B().unpack(str[start:end])
      self.pc_to_mcu_heartbeat_error = bool(self.pc_to_mcu_heartbeat_error)
      self.motor_to_mcu_heartbeat_error = bool(self.motor_to_mcu_heartbeat_error)
      self.can_error = bool(self.can_error)
      self.lin_error = bool(self.lin_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_6B().pack(_x.motorErrorIndex, _x.pc_to_mcu_heartbeat_hz, _x.pc_to_mcu_heartbeat_error, _x.motor_to_mcu_heartbeat_error, _x.can_error, _x.lin_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mode = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.motorErrorIndex, _x.pc_to_mcu_heartbeat_hz, _x.pc_to_mcu_heartbeat_error, _x.motor_to_mcu_heartbeat_error, _x.can_error, _x.lin_error,) = _get_struct_6B().unpack(str[start:end])
      self.pc_to_mcu_heartbeat_error = bool(self.pc_to_mcu_heartbeat_error)
      self.motor_to_mcu_heartbeat_error = bool(self.motor_to_mcu_heartbeat_error)
      self.can_error = bool(self.can_error)
      self.lin_error = bool(self.lin_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6B = None
def _get_struct_6B():
    global _struct_6B
    if _struct_6B is None:
        _struct_6B = struct.Struct("<6B")
    return _struct_6B
