# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from twinny_msgs/MonitorPowerBoard.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MonitorPowerBoard(genpy.Message):
  _md5sum = "d786489e7a443dba4376961f64ea7161"
  _type = "twinny_msgs/MonitorPowerBoard"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header 

string Mode

string voltage_flag
string charge_current_flag

string robot_power_on_mode

bool motor_relay_error
bool robot_power_relay_error
bool pc_switch_error
bool pc_boot_up_error
bool pc_boot_off_error
bool pc_down_error
bool charge_relay_error
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','Mode','voltage_flag','charge_current_flag','robot_power_on_mode','motor_relay_error','robot_power_relay_error','pc_switch_error','pc_boot_up_error','pc_boot_off_error','pc_down_error','charge_relay_error']
  _slot_types = ['std_msgs/Header','string','string','string','string','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Mode,voltage_flag,charge_current_flag,robot_power_on_mode,motor_relay_error,robot_power_relay_error,pc_switch_error,pc_boot_up_error,pc_boot_off_error,pc_down_error,charge_relay_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MonitorPowerBoard, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Mode is None:
        self.Mode = ''
      if self.voltage_flag is None:
        self.voltage_flag = ''
      if self.charge_current_flag is None:
        self.charge_current_flag = ''
      if self.robot_power_on_mode is None:
        self.robot_power_on_mode = ''
      if self.motor_relay_error is None:
        self.motor_relay_error = False
      if self.robot_power_relay_error is None:
        self.robot_power_relay_error = False
      if self.pc_switch_error is None:
        self.pc_switch_error = False
      if self.pc_boot_up_error is None:
        self.pc_boot_up_error = False
      if self.pc_boot_off_error is None:
        self.pc_boot_off_error = False
      if self.pc_down_error is None:
        self.pc_down_error = False
      if self.charge_relay_error is None:
        self.charge_relay_error = False
    else:
      self.header = std_msgs.msg.Header()
      self.Mode = ''
      self.voltage_flag = ''
      self.charge_current_flag = ''
      self.robot_power_on_mode = ''
      self.motor_relay_error = False
      self.robot_power_relay_error = False
      self.pc_switch_error = False
      self.pc_boot_up_error = False
      self.pc_boot_off_error = False
      self.pc_down_error = False
      self.charge_relay_error = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.voltage_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.charge_current_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.robot_power_on_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.motor_relay_error, _x.robot_power_relay_error, _x.pc_switch_error, _x.pc_boot_up_error, _x.pc_boot_off_error, _x.pc_down_error, _x.charge_relay_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.voltage_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.voltage_flag = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.charge_current_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.charge_current_flag = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_power_on_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.robot_power_on_mode = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.motor_relay_error, _x.robot_power_relay_error, _x.pc_switch_error, _x.pc_boot_up_error, _x.pc_boot_off_error, _x.pc_down_error, _x.charge_relay_error,) = _get_struct_7B().unpack(str[start:end])
      self.motor_relay_error = bool(self.motor_relay_error)
      self.robot_power_relay_error = bool(self.robot_power_relay_error)
      self.pc_switch_error = bool(self.pc_switch_error)
      self.pc_boot_up_error = bool(self.pc_boot_up_error)
      self.pc_boot_off_error = bool(self.pc_boot_off_error)
      self.pc_down_error = bool(self.pc_down_error)
      self.charge_relay_error = bool(self.charge_relay_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.voltage_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.charge_current_flag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.robot_power_on_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7B().pack(_x.motor_relay_error, _x.robot_power_relay_error, _x.pc_switch_error, _x.pc_boot_up_error, _x.pc_boot_off_error, _x.pc_down_error, _x.charge_relay_error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.voltage_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.voltage_flag = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.charge_current_flag = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.charge_current_flag = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot_power_on_mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.robot_power_on_mode = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.motor_relay_error, _x.robot_power_relay_error, _x.pc_switch_error, _x.pc_boot_up_error, _x.pc_boot_off_error, _x.pc_down_error, _x.charge_relay_error,) = _get_struct_7B().unpack(str[start:end])
      self.motor_relay_error = bool(self.motor_relay_error)
      self.robot_power_relay_error = bool(self.robot_power_relay_error)
      self.pc_switch_error = bool(self.pc_switch_error)
      self.pc_boot_up_error = bool(self.pc_boot_up_error)
      self.pc_boot_off_error = bool(self.pc_boot_off_error)
      self.pc_down_error = bool(self.pc_down_error)
      self.charge_relay_error = bool(self.charge_relay_error)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7B = None
def _get_struct_7B():
    global _struct_7B
    if _struct_7B is None:
        _struct_7B = struct.Struct("<7B")
    return _struct_7B
