main:
  hz                  : 20 
  spinner_count       : 1
  device              : /dev/input/js0  ## 조이스틱 디바이스 경로
  deadzone            : 0.1            ## 조이스틱 민감도

alive:
  hz                   : 20          ## heartbeat 보고 주기

logger:
  debug               : 1             ## debug 옵션 (0: off, 그외 : on)
  hz                  : 50            ## thread 동작 속도
  suffix              : _driving      ## 로그 파일 이름 뒤에 붙는 suffix
  dir_name            : log           ## 로그 파일 저장 디렉토리
  max_log_per_write   : 50            ## 한번에 기록 할 최대 로그 갯수
  auto_write_interval : 500           ## millisecond 로그 파일을 자동으로 기록하는 주기