main:
  hz                    : 50 
  spinner_count         : 1
  io_signal_publish_hz  : 5           ## io signal publish 주기 (변화가 있을 때는 즉시)

alive:
  hz: 20                              ## heartbeat 보고 주기          

logger:
  debug               : 1             ## debug 옵션 (0: off, 그외 : on)
  hz                  : 50            ## thread 동작 속도
  suffix              : _carrybot     ## 로그 파일 이름 뒤에 붙는 suffix
  dir_name            : log           ## 로그 파일 저장 디렉토리
  max_log_per_write   : 50            ## 한번에 기록 할 최대 로그 갯수
  auto_write_interval : 500           ## millisecond 로그 파일을 자동으로 기록하는 주기

comm:
  comm_type   : "ModbusTCP"           ## 통신 방식 (ModbusTCP, RTU(232, 485))
  ip          : "192.168.11.202"      ## wago ip 주소
  port        : 502                   ## wago port 
  retry_count : 3                     ## wago 연결 시도 횟수
  retry_turm  : 2                     ## wago 연결 시도 간격
  debug       : 0                     ## debug 옵션 (0: off, 그외 : on)